local status, treesitter = pcall(require, "nvim-treesitter.configs")
if not status then
	return
end

treesitter.setup({
	highlight = {
		enable = true,
	},
	indent = { enable = true },
	autotag = { enable = true },
	ensure_installed = {
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "cpp",
    "css",
    "dockerfile",
    "dot",
    "gdscript",
    "git_rebase",
    "gitattributes",
    "gitignore",
    "godot_resource",
    "graphql",
    "html",
    "http",
    "javascript",
    "json",
    "latex",
    "llvm",
    "lua",
    "make",
    "markdown",
    "php",
    "phpdoc",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "swift",
    "todotxt",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "wgsl",
    "yaml",
	},
	auto_install = true,
})
